### ISSUE TITLE
Problems with translation

### ISSUE THREAD

**Issue by rodfersou** [collective/tutorial.todoapp#14]
Hi I'm trying to translate te tutorial to braziliam portuguese, but it is just not working following the steps mentionated into the README.txt file.. I could get partial translation working following this link http://sphinx-doc.org/latest/intl.html .. but now I don't know why I can't translate the README.rst incluted into index.rst file... 

My translation fork is https://github.com/rodfersou/tutorial.todoapp could you help me plese?

Since now thanks

**Comment by rodfersou** [comment]
My main problem was with doctrees directory.. I deleted them and the translation start working!

Since now thanks

**Comment by zupo** [comment]
Hey @rodfersou I just updated the tutorial to Plone 4.3, so translations will ne to be updated at some point also :).
