### ISSUE TITLE
in chapter 0, change so that we are not checking boxes in the "add plone site" page

### ISSUE THREAD

**Issue by tkimnguyen** [collective/tutorial.todoapp#16]
I believe we recently discovered that adding products in the Add Plone Site page can lead to random GS profiles being run or not run. Should stick to activating products via Site Setup -> Add-ons

**Comment by smcmahon** [comment]
That's a bug we've got to fix -- not just work around. So, no doc changes needed.

Also, avoiding activation on adding a site doesn't necessarily avoid the problem.
