### ISSUE TITLE
self.view() not needed, using output is just fine

### ISSUE THREAD

**Issue by plamut** [collective/tutorial.todoapp#5]
https://github.com/collective/tutorial.todoapp/blob/master/src/tutorial/todoapp/tests/test_todo_view.py#L66

There is no need to use self.view() on the line linked above, because modification date has already been set when self.view() is called for the first time and the output stored in the "output". We can just use this ouput, jut like on any other lines in this test.

**Comment by zupo** [comment]
Thanks!
