### ISSUE TITLE
"Brulé" instead of "Brul\xe9"?

### ISSUE THREAD

**Issue by plamut** [collective/tutorial.todoapp#6]
https://github.com/collective/tutorial.todoapp/blob/master/src/tutorial/todoapp/tests/test_todo_view.py#L60

A suggestion: the test_listing_table test would be slightly more readable, if the string with a non-ascii char ("Brulé") is written in the code in the same way.
Currently the the 'é' char is written in two different ways (as 'é' and '\xe9').

**Comment by zupo** [comment]
Thanks!
