### ISSUE TITLE
typo in chapter 3 (same typo in chapter 4)

### ISSUE THREAD

**Issue by mjtrac** [collective/tutorial.todoapp#7]
First, thank you, thank you, thank you!  This is by far the cleanest and most understandable tutorial I've yet found to anything plone related.  Bravo!  I really hope this gets used as a model for Plone tutorials in the future.  When someone is trying to learn what seems like ten different things, each using different syntax, each involving "special" places that become second-nature to experienced users, this sort of clarity is a godsend.  

Please change the file reference in the text below (from the readthedocs version) from `test_setup` to `test_setup.py`

First add the following snippet to `test_setup` to verify that your Folders
have the `todo` view on the `Display` drop-down menu.

One other item I'll mention, though it may be specific to my setup.  I see the following error in my console output, presumably from when I created a todo item:

2012-12-17 09:46:07 WARNING plone.supermodel plone.dexterity.schema.generated.Plone_0_todo_item is not an instance of SchemaClass. This can happen if the first base class of a schema is not a SchemaClass. See https://bugs.launchpad.net/zope.interface/+bug/791218

**Comment by zupo** [comment]
Fixed the typo, thanks for the suggestion!

About the other thing, I have no idea what it could be. I'll close this ticket now, please create a separate ticket if you want to pursue it further.
